name: tree_app
description: A mobile app for tree analysis and measurement
publish_to: 'none' # мы не публикуем этот пакет

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- наши зависимости ---
  image_picker: ^1.1.1
  camera: ^0.11.0+2
  dio: ^5.6.0

  # Material Design и иконки
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
